#!/bin/bash
set -e

cd /app

export PORT=${PORT:-30000}

CONFIG=/tmp/nginx.conf

SITE_FILES=/app/webroot

# Allow loaderio only if LOADERIO_TOKEN is set
if [ -n "$LOADERIO_TOKEN" ]; then
  echo $LOADERIO_TOKEN > /tmp/$SITE_FILES/$LOADERIO_TOKEN.txt
fi

cat <<EOF > $CONFIG
worker_processes 4;
worker_rlimit_nofile 40000;
pid /tmp/nginx.pid;
error_log stderr;
daemon off;

events {
  worker_connections 20000;
}

http {
  sendfile on;
  tcp_nopush on;
  tcp_nodelay on;
  keepalive_timeout 65;
  types_hash_max_size 2048;
  server_names_hash_bucket_size 64;

  client_body_temp_path /tmp/client_body;
  proxy_temp_path /tmp/proxy;
  fastcgi_temp_path /tmp/fastcgi;

  include /etc/nginx/mime.types;
  default_type application/octet-stream;

  access_log off;
  error_log stderr;

  gzip on;
  gzip_disable "msie6";

  open_file_cache          max=2000 inactive=525600m;
  open_file_cache_valid    525600m;
  open_file_cache_min_uses 1;
  open_file_cache_errors   on;

  server {
    listen $PORT;
    port_in_redirect off;
    root $SITE_FILES;
    index index.html;
    expires 2m;
    location /server-status {
        allow 10.0.0.0/8;
        deny  all;
        stub_status on;
    }
  }
}
EOF

exec /usr/sbin/nginx -c /tmp/nginx.conf
